In [73]:
#예제 1
symbols = "$*&!@"
codes = []
for symbol in symbols:
    codes.append(ord(symbol))
codes

[36, 42, 38, 33, 64]

In [74]:
#예제 2
symbols = "$*&!@"
codes = [ord(symbol) for symbol in symbols]
codes

[36, 42, 38, 33, 64]

In [76]:
#예제 3
x = '"!~$$*&!@'
dummy = [ord(x) for x in x]

print(x)
print(dummy)

"!~$$*&!@
[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [78]:
#예제 4
symbols = '"!~$$*&!@'
beyond_ascil = [ord(s) for s in symbols if ord(s) > 32]

print(beyond_ascil)

[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [79]:
#예제 5
symbols = '"!~$$*&!@'
beyond_ascil = list(filter(lambda c: c > 64 , map(ord, symbols)))

print(beyond_ascil, '\n')

print(f"Map function:\n>>>{map(ord, symbols)}")
print(f"List after map:\n>>>{list(map(ord, symbols))}")


[126] 

Map function:
>>><map object at 0x7b0fdf075660>
List after map:
>>>[34, 33, 126, 36, 36, 42, 38, 33, 64]


In [80]:
#예제 6
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
tshirts = [(color, size) for color in colors for size in sizes]

print(tshirts)

for color in colors:
      for size in sizes:
          print((color, size))

[('black', 'S'), ('black', 'M'), ('black', 'L'), ('white', 'S'), ('white', 'M'), ('white', 'L')]
('black', 'S')
('black', 'M')
('black', 'L')
('white', 'S')
('white', 'M')
('white', 'L')


In [82]:
#예제 7
symbols = "!#^&&#"
ord_s = tuple(ord(s) for s in symbols if ord(s))

print(ord_s)

(33, 35, 94, 38, 38, 35)


In [83]:
#예제 7
import array
ord_s = array.array('I', (ord(symbol) for symbol in symbols)) #타입 지정 형식 int형 배열임을 뜻함
print(ord_s)

array('I', [33, 35, 94, 38, 38, 35])


In [84]:
#예제 8
colors = ['black', 'white']
sizes = ['S', 'M', 'L']
for tshirt in ('{} {}'.format(c,s) for c in colors for s in sizes):
    print(tshirt)

black S
black M
black L
white S
white M
white L


In [6]:
#예제 9
lax_coordinates = (33.9425, -118.408056)
cuty, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)
traveler_ids = [('USA', '31195855'),
                ('BRA', 'CE342567'),
                ('ESP','XDA205856')]
for passport in sorted(traveler_ids):
    print('%s/%s'% passport)
    print('{}/{}'.format(passport[0], passport[1]))
    print(f'{passport[0]}/{passport[1]}')

BRA/CE342567
BRA/CE342567
BRA/CE342567
ESP/XDA205856
ESP/XDA205856
ESP/XDA205856
USA/31195855
USA/31195855
USA/31195855


In [85]:
#예제 10
for country, _ in traveler_ids:
    print(country)

USA
BRA
ESP


In [87]:
city, year, pop, chg, area = ('Tokyo', 2003, 32450, 0.66, 8014)

In [88]:
print('%s/%s'%passport)

USA/31195855


In [89]:
#예제 11
lax_coordinates = (33.9425, -118.408056)
latitude, longitude = lax_coordinates # 튜플 언패킹
print(latitude)
print(longitude)

33.9425
-118.408056


In [90]:
#예제 12
a = 10; b = 20
b, a = a, b
print(a, b)

20 10


In [91]:
#예제 13-1
divmod(20, 8)

(2, 4)

In [92]:
#예제 13-2
t = (20,8)
divmod(*t) # 튜플 언패킹 *을 넣어줌으로써 변수 2개 병렬 할당 가능

(2, 4)

In [93]:
#예제 13-3
quotient, remainder = divmod(*t)
quotient, remainder

(2, 4)

In [94]:
#예제 14
import os
_, filename = os.path.split('/home/luciano/.ssh/idrsa.pub')
filename

'idrsa.pub'

In [95]:
#예제 15-1
a, b, *rest = range(5) #*resr : 나머지는 가변형 데이터로 받겠다는 뜻.
a, b, rest

(0, 1, [2, 3, 4])

In [96]:
#예제 15-2
a, b, *rest = range(3)
a, b, rest

(0, 1, [2])

In [97]:
#예제 15-3
a, b, *rest = range(2)
a, b, rest

(0, 1, [])

In [98]:
#예제 16-1
a, *body, c, d = range(5)
a, body, c, d

(0, [1, 2], 3, 4)

In [99]:
#예제 16-2
*head, b, c, d = range(5)
head, b, c, d

([0, 1], 2, 3, 4)

In [121]:
#예제 17
metro_areas = [
    ('Tokyo', 'JP', 36.933, (35, 139)),
    ('Delhi NCR', 'IN', 21.935, (28, 77)),
    ('Mexico City', 'MX', 20.142, (19, -99)),
    ('New York-Newark', 'US', 20.104, (40, -74)),
    ('Sao Paulo', 'BR', 19.649, (-23, -46)),
]
print('{:15} | {:^9} | {:^9}'.format('', 'lat.', 'long.'))
fmt = '{:15} | {:9.4f} | {:9.4f}'
for name, cc, pop, (latitude, longitude) in metro_areas:
    if longitude <= 0:
        print(fmt.format(name, latitude, longitude))

                |   lat.    |   long.  
Mexico City     |   19.0000 |  -99.0000
New York-Newark |   40.0000 |  -74.0000
Sao Paulo       |  -23.0000 |  -46.0000


In [122]:
#예제 18-1
from collections import namedtuple
City = namedtuple('City','name country population coordinates')
tokyo = City('Tokyo', 'JP', 36.933, (35.689, 139.691))
tokyo

City(name='Tokyo', country='JP', population=36.933, coordinates=(35.689, 139.691))

In [123]:
#예제 18-2
tokyo.population

36.933

In [124]:
#예제 18-3
tokyo.coordinates

(35.689, 139.691)

In [125]:
#예제 18-4
tokyo[1]

'JP'

In [126]:
#예제 19-1
City._fields

('name', 'country', 'population', 'coordinates')

In [128]:
#예제 19-2
LatLong = namedtuple('LatLong', 'lat long')
delhi_data = ('Delhi NCR', 'IN', 21.935, LatLong(28.613, 77.208))
delhi = City._make(delhi_data)
delhi._asdict()

{'name': 'Delhi NCR',
 'country': 'IN',
 'population': 21.935,
 'coordinates': LatLong(lat=28.613, long=77.208)}

In [129]:
#예제 19-3
for key, value in delhi._asdict().items(): #key value 추출
    print(key + ':', value)

name: Delhi NCR
country: IN
population: 21.935
coordinates: LatLong(lat=28.613, long=77.208)


In [130]:
#예제 20-1
ㅣ = [10, 20, 30, 40, 50, 60]
ㅣ[:2]

[10, 20]

In [131]:
#예제 20-2
ㅣ[2:]

[30, 40, 50, 60]

In [133]:
#예제 20-3
ㅣ[:3] #3번 인덱스에서 분할

[10, 20, 30]

In [134]:
#예제 20-4
ㅣ[3:]

[40, 50, 60]

In [135]:
#예제 21
invoice  ="""
0.....6..................25........33......40.......
1909  Pimoroni              $17.50    3     $52.50
1489  6mm Tactile           $4.95     2     $9.90
"""

SKU = slice(0, 6)
DESCRIPTION = slice(6, 25)
UNIT_PRICE = slice(25, 33)
QUANTITY = slice(33, 40)
ITEM_TOTAL = slice(40, None)

line_items = invoice.split('\n')[2:]

for item in line_items:
    print(item[UNIT_PRICE], item[DESCRIPTION])

   $17.5 Pimoroni           
   $4.95 6mm Tactile        
 


In [144]:
#예제 22-1
l = list(range(10))
l

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [145]:
#예제 22-2
l[2:5] = [20,30]
l

[0, 1, 20, 30, 5, 6, 7, 8, 9]

In [146]:
#예제 22-3
del l[5:7]
l

[0, 1, 20, 30, 5, 8, 9]

In [147]:
#예제 22-4
l[3::2] = [11, 22]
l

[0, 1, 20, 11, 5, 22, 9]

In [140]:
#예제 23
l[2:5] = 100 #오류

TypeError: can only assign an iterable

In [148]:
#예제 24
l[2:5] = [100]
l

[0, 1, 100, 22, 9]

In [149]:
#예제 25-1
l = [1, 2, 3]
l * 5

[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]

In [150]:
#예제 25-2
5 * 'abcd'

'abcdabcdabcdabcdabcd'

In [151]:
#예제 26-1
board = [['_'] * 3 for i in range(3)]
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [152]:
#예제 26-2
board[1][2] = 'x'
board

[['_', '_', '_'], ['_', '_', 'x'], ['_', '_', '_']]

In [153]:
#예제 27-1
weird_board = [['_'] * 3] * 3
weird_board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]

In [154]:
#예제 27-2
weird_board[1][2] = '0'
weird_board

[['_', '_', '0'], ['_', '_', '0'], ['_', '_', '0']]

In [155]:
#예제 28
row = ['_'] * 3 #한번 생성한 걸 여러번 사용
board = []
for i in range(3):
    board.append(row)

board[1][2] = 'x'
board

[['_', '_', 'x'], ['_', '_', 'x'], ['_', '_', 'x']]

In [156]:
#예제 29
board = []
for i in range(3):
    row = ['_'] * 3 #반복문마다 새로 생성. 참조주소가 달라서 변화시킨다해도 나머지가 바뀌지 않음
    board.append(row)
print(board)
board[2][0] = 'x'
board

[['_', '_', '_'], ['_', '_', '_'], ['_', '_', '_']]


[['_', '_', '_'], ['_', '_', '_'], ['x', '_', '_']]

In [157]:
#예제 30-1
l = [1, 2, 3]
id(l)

135308600971968

In [158]:
#예제 30-2
l *= 2
l

[1, 2, 3, 1, 2, 3]

In [159]:
#예제 30-3
id(l)

135308600971968

In [160]:
#예제 31-1
t = (1, 2, 3)
id(t)

135308600970432

In [161]:
#예제 31-2
t *= 2
id(t)

135308599427136

In [162]:
#예제 32
t = (1, 2, [30, 40])
print(t)

t[2] += [50, 60] #덧셈 먼저 하고 실행 결과를 확인하기 때문에 a도 맞고 오류가뜨는 b도 맞다. 이때 t[2] = t[2] + [50, 60]은 실행 결과를 보고 그걸 튜플에 넣는거기 때문에 확인과정에서
#오류가 생기고 t는 바뀌지 않는다.

"""
a. t는 (1, 2, [30, 40, 50, 60])이 된다.
b. '튜플 객체는 항목 할당을 지원하지 않는다'는 메세지와 함께 TypeError가 발생한다.
c. a와 b 둘 다 틀리다.
d. a와 b 둘 다 맞다.
"""

(1, 2, [30, 40])


TypeError: 'tuple' object does not support item assignment

In [163]:
#예제 33
print(t)

(1, 2, [30, 40, 50, 60])


In [164]:
#예제 34-1
fruits = ['grape', 'raspberry', 'apple', 'banana']
sorted(fruits)

['apple', 'banana', 'grape', 'raspberry']

In [165]:
#예제 34-2
fruits

['grape', 'raspberry', 'apple', 'banana']

In [166]:
#예제 34-3
sorted(fruits, reverse=True)

['raspberry', 'grape', 'banana', 'apple']

In [167]:
#예제 34-4
sorted(fruits, key=len)

['grape', 'apple', 'banana', 'raspberry']

In [168]:
#예제 35-1
sorted(fruits, key=len, reverse=True)

['raspberry', 'banana', 'grape', 'apple']

In [169]:
#예제 35-2
fruits

['grape', 'raspberry', 'apple', 'banana']

In [170]:
#예제 35-3
fruits.sort() #기존 리스트를 바꿈
fruits

['apple', 'banana', 'grape', 'raspberry']

In [171]:
#예제 36
from array import array
from random import random

floats = array('d', (random() for i in range(10**7))) #double타입 배열 생성
floats[-1]

0.2390636773131889

In [172]:
#예제 37-1
with open('floats.bin', 'wb') as f:
    floats.tofile(f)
floats2 = array('d')

with open ('floats.bin', 'rb') as f:
    floats2.fromfile(f, 10**7)

floats2[-1]

0.2390636773131889

In [173]:
#예제 37-2
floats == floats2

True

In [174]:
#예제 38-1
import array
numbers = array.array('h', [-2, -1, 0, 1, 2]) #타입코드 h : sigh shirt int
memv = memoryview(numbers)
len(memv)

5

In [175]:
#예제 38-2
memv[0]

-2

In [176]:
#예제 38-3
memv_oct = memv.cast('B') #타입코드 B : unsigned char위에 int타입코드는 2바이트였는데 1바이트인 char형으로 변형하여서 2개씩 출력된다.
memv_oct.tolist() #254, 255 = -2 255, 255 = -1 ...

[254, 255, 255, 255, 0, 0, 1, 0, 2, 0]

In [178]:
#예제 38-4
memv_oct[5] = 4
numbers

array('h', [-2, -1, 1024, 1, 2])

In [179]:
#예제 39-1
import numpy
a = numpy.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [180]:
#예제 39-2
type(a)

numpy.ndarray

In [181]:
#예제 40-1
a.shape

(12,)

In [182]:
#예제 40-2
a.shape = 3,4
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [183]:
#예제 41-1
a[2]

array([ 8,  9, 10, 11])

In [185]:
#예제 41-2
a[2,1]

9

In [184]:
#예제 41-3
a[:,1]

array([1, 5, 9])

In [186]:
#예제 42
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [201]:
#예제 43-1
from collections import deque
dq = deque(range(10), maxlen=10)
dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [203]:
#예제 43-2
dq.rotate(3)
dq

deque([4, 5, 6, 7, 8, 9, 0, 1, 2, 3])

In [204]:
#예제 43-3
dq.rotate(-4)
dq

deque([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [205]:
#예제 44-1
dq.appendleft(-1)
dq

deque([-1, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [206]:
#예제 44-2
dq.extend([11, 22, 33])
dq

deque([0, 1, 2, 3, 4, 5, 6, 11, 22, 33])

In [207]:
#예제 44-3
dq.extendleft([10, 20, 30, 40])
dq

deque([40, 30, 20, 10, 0, 1, 2, 3, 4, 5])